export function isValidName(name: string): boolean {
  // Must be a valid JS identifier and not a reserved keyword
  // Use regex for identifier, and a set of reserved words
  const identifierRegex = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
  const reservedWords = new Set([
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'debugger',
    'default',
    'delete',
    'do',
    'else',
    'export',
    'extends',
    'finally',
    'for',
    'function',
    'if',
    'import',
    'in',
    'instanceof',
    'new',
    'return',
    'super',
    'switch',
    'this',
    'throw',
    'try',
    'typeof',
    'var',
    'void',
    'while',
    'with',
    'yield',
    'let',
    'enum',
    'await',
    'implements',
    'package',
    'protected',
    'static',
    'interface',
    'private',
    'public',
  ]);
  return identifierRegex.test(name) && !reservedWords.has(name);
}
